## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [19]:
import numpy as np
import pandas as pd
from scipy import stats

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [20]:
samples = np.random.normal(loc = 100, scale = 15, size = 1000)
samples

array([125.20050744,  97.55268427, 107.90280542,  87.10547081,
        86.19302948,  74.00478853, 103.71027009, 100.79803558,
        84.51656748,  86.9621688 , 124.29803987,  74.91333954,
       104.36658919,  82.30133301, 107.87437834, 117.83299242,
       115.56088016,  93.58372225,  79.18341206, 106.20924282,
       106.95469732,  88.76728152,  71.04336919, 105.34134266,
        95.02409208,  85.72841147,  72.4226461 ,  81.67780077,
        89.39211575, 109.82516828, 104.45296196,  99.88326325,
        93.34758143,  92.36123584,  97.12864271,  60.45397306,
        95.83104088, 107.00815677,  93.02205028, 101.06043193,
        97.19449555,  80.85281452, 112.92398484, 100.59318968,
        86.58875711, 126.71843867,  83.09192101, 116.69049431,
       107.35567284, 101.1640209 , 123.51466752, 104.06605482,
       111.61831011, 101.35953664, 106.34027265, 107.72094691,
        78.37663653, 124.72455528,  78.57642544,  61.81264734,
        72.1893945 ,  76.03257151, 106.56601565, 111.07608418,
        82.33777331, 120.11317607,  88.71121432, 117.5888077 ,
        92.1302889 , 115.2150546 , 107.03495664,  80.13602555,
        90.06032076,  92.8238707 , 136.82644122, 109.76694855,
       110.73323661, 118.71223606,  80.54419664,  83.62263558,
        97.7862348 ,  98.84015116,  88.97357706, 100.07333   ,
        75.1885682 , 102.9485562 ,  96.34327863,  99.83706011,
       121.00916522, 105.84547199,  94.35779019, 105.05599945,
        92.48062035, 119.10286014, 104.54536616, 102.79089067,
       106.04164644, 102.08360145, 121.74770181,  96.76504559,
        96.33686191,  91.99615254, 101.45569943, 106.17054101,
       108.70450744,  89.9705514 , 100.38083052, 147.60326158,
        88.08777949, 104.97228758, 113.26773868,  92.68958621,
        79.87159927,  98.52149668,  92.97039807,  86.46149035,
       101.46531994, 106.67506234,  80.72375402, 103.11828341,
        70.25438432, 110.88423629,  95.22538419, 119.31574186,
        71.1400678 , 110.32953312, 126.44061851, 111.87861938,
       104.3166261 ,  88.79204508,  52.2603512 , 102.15667565,
       107.01770468,  92.45443958, 110.41207546,  77.9096779 ,
       101.35206126, 103.2039488 ,  73.17789221,  92.1422292 ,
        84.50432488,  92.97603662, 111.45246669, 108.56508984,
        96.56975154,  90.03794894, 103.34426579,  82.65679036,
        92.97776514, 109.79713199,  96.28039943, 106.16040924,
       108.51710627,  72.39770461, 113.20615029, 121.28412169,
       107.0708105 , 124.17804742, 117.09257537, 108.87476671,
        99.11951313,  87.26366364, 126.33241525, 104.15343014,
        91.880562  ,  83.29425145,  92.14710181, 103.54537116,
        91.50453383,  87.86059715, 106.35966287, 115.7795251 ,
       105.39192973,  86.26232294, 101.43594407, 111.38522538,
        97.23564163,  84.68019881,  99.06349591, 113.1565262 ,
        97.29987562, 110.67846038, 115.48350611, 125.45254254,
       103.35693526, 100.57054109, 110.62158599, 117.81410141,
       127.64297603,  77.88597459,  97.2581578 , 110.58028668,
       110.98947012, 111.62668872,  84.7590232 ,  95.50761906,
       138.91508128,  83.11186993,  87.91952786,  91.98487509,
        98.86221792, 116.68174492, 101.05509995, 109.03945365,
        92.95172106, 105.06306833,  98.16612078, 100.20245073,
        88.74637097, 100.76326785,  99.98619226, 115.80901662,
       121.90294301,  82.31668663, 105.62151217, 124.81546536,
       105.73326206, 111.84891521, 124.96135635, 109.78581482,
       101.35046626,  89.99903662,  91.81028004,  78.13066586,
       129.05365048, 113.53958534,  97.23037088, 105.57008478,
       113.75295229, 114.87554827, 101.33055689,  92.14895221,
       115.77535146, 134.58462131,  72.10186484, 104.49085749,
       106.17848004,  82.57652323, 109.82298372, 104.18659815,
        98.16607003,  81.84782707,  94.27331369, 116.26084708,
       100.13036798,  96.35903645, 101.30992134,  95.02157816,
       108.79979756,  95.48804429, 108.64119536, 110.70571508,
       113.5424536 ,  81.61307117, 107.185278  , 108.69118782,
       107.95949598,  83.88319807, 103.8508582 , 106.45972157,
        85.41218743,  88.21662418,  94.73466676,  85.18183839,
        99.9621749 , 100.04178334,  71.26775279, 108.00426466,
        93.21571042, 109.03525122, 105.62804447,  77.35495281,
        81.92371766, 104.25731921, 101.91615485,  98.88328104,
        79.30965227,  99.24660575,  87.62198556, 127.86609828,
        83.83263025, 104.49523708,  97.2431768 ,  96.94192127,
        87.14648281, 110.51131887, 105.02121104,  96.1991366 ,
        74.00128358,  85.26194112,  93.03345696,  98.62660041,
        88.88303869,  94.41417512,  98.73442411, 112.32713556,
        95.3277685 ,  91.98295629, 109.80517508,  94.91935485,
        90.4922162 , 128.10365225, 113.86961651,  94.24515922,
        97.3667263 , 129.6551623 , 115.10326313,  99.1979069 ,
        86.15307052, 101.02153808, 111.59668497, 102.52325142,
        83.74729609,  91.38651401,  83.72315455,  99.04858916,
        96.70392633, 109.0717807 ,  90.66426128, 112.67527232,
       108.89295937,  87.28458571, 104.86699388,  74.9924182 ,
       120.07039456, 113.99480882,  86.63184461,  80.22701366,
       103.59107517,  71.72227338, 126.40081076,  91.24752916,
        88.27920799,  68.32381137, 126.84373743, 117.48491989,
       104.62951039, 102.71154418,  87.73228208, 105.18389742,
       100.6678225 ,  96.74968675,  92.96895229,  98.67484118,
        97.93709528,  71.92989434, 102.24493633, 105.01440702,
       105.97096206,  64.22494715, 121.65940029,  92.13444914,
        74.57732863, 108.52350572, 107.777364  ,  78.07644019,
        88.36840139, 115.82620019,  72.50488756,  99.8454261 ,
       104.44656116, 103.6722693 , 109.88958852, 116.18817733,
       100.89450969, 106.18910183, 113.29363452, 106.72505917,
       112.39238804,  87.35631474, 109.48737013, 103.95796332,
        68.56168377, 115.5120338 ,  61.75520506,  94.29557154,
        85.75526541, 101.76523714, 117.03881061, 137.7677854 ,
       137.26629065, 111.88464396,  71.97638533, 107.76782007,
       124.89175969,  96.44218557, 106.06685898, 108.24411518,
        85.69909283,  66.79108059, 107.10291116,  66.39935791,
       113.9799129 , 149.81598641, 105.3103909 ,  95.85788468,
        83.6410725 ,  85.43504873, 101.75280061,  73.79154816,
        88.72394995, 118.19690073, 118.93532537, 118.3000412 ,
        93.0024504 , 104.78489154, 102.85878534,  92.9610498 ,
       110.662407  ,  86.0070182 ,  99.79139861,  97.21108984,
        98.40144417, 107.03356058,  95.71703539,  94.65897001,
        83.72520586,  91.6844324 , 103.99084712,  76.29466407,
        96.20728066, 101.2637463 , 104.45633816, 102.48807588,
        96.70697022, 103.77401535,  97.28122112,  82.24249605,
        90.75146754, 109.99276537,  97.9017393 , 103.55520063,
        98.28940012,  92.84442983,  92.66701005,  78.44514628,
       121.14213114,  96.83216744,  65.96569566, 108.69883379,
        99.43260444, 104.77781062,  79.08022204, 107.33909476,
        85.66092597, 104.76505761,  76.452085  ,  87.6442425 ,
        89.85242223, 106.59986818, 109.03155765, 110.99513385,
       124.92409621, 106.27497373,  87.19217254,  94.41048042,
       106.80328047,  96.66832079,  90.8997941 ,  88.41609801,
        76.86393906,  93.23522863,  99.80282047,  98.41928131,
       113.69768799,  76.68851723, 104.02228546, 135.22699947,
       107.5684185 , 103.66170969,  74.09352078,  92.10164891,
       101.00100982,  87.60696659,  83.29166928, 105.77920453,
        86.88353947, 116.40223899, 130.84320883, 115.27201533,
       131.38892923, 118.76808579, 112.37800244, 110.80083928,
       106.18715012,  76.14001438,  95.45249268,  96.85070151,
       109.592486  , 122.43612527,  85.86546811,  94.54336374,
        74.2779936 , 104.06907551, 103.55940263, 104.267265  ,
        89.732556  , 102.26439483,  99.84330514,  88.28888772,
       100.54940782, 107.09759802,  96.29047978, 112.10912795,
        82.80090471,  76.52824691, 115.13024914,  96.78181746,
        96.03773887, 104.99502006,  99.96675357,  94.70887947,
        99.53030475, 130.39848783,  90.45540944, 123.47811484,
        92.23473732,  95.30131902, 111.3494054 ,  88.80058262,
       105.89693369, 110.81994229, 117.98642031, 110.32265239,
        75.08042257, 134.31966423, 120.91781246, 118.16726892,
        94.88976975,  65.45895141, 105.34699607, 111.77621399,
       110.26150247, 113.31189204,  97.03395385,  75.7474699 ,
       113.12480197, 101.92907963,  97.32404198,  94.71251782,
        76.21121057,  83.39849674, 120.27934918,  98.01890827,
        92.03587541,  97.68547373,  92.48687313,  84.78110094,
       102.95852304, 105.22170042,  97.41522283, 104.39895185,
       110.59364759, 105.16569142,  78.72525145,  89.10885066,
        99.19484965,  77.42562605, 108.84597083,  93.68374436,
       106.97157701,  89.77191657,  67.24756543,  87.53625765,
        92.15646234, 101.53609322,  70.11360564,  87.89215392,
       116.84791778, 111.00754514,  84.02396842, 100.02886151,
        55.83458504, 121.35656803,  86.15039438,  87.90528157,
        95.33052863, 105.72589378, 111.77681818, 106.25820547,
       124.40971629,  91.73142592,  99.61229508,  99.51000514,
       109.37371169,  92.83741007, 107.69532418, 105.58531054,
        95.95182866,  80.41786736,  90.23172034,  91.29404692,
        93.26258972,  89.71653357, 107.54843565,  81.31787699,
       108.90852531,  90.82770417,  85.89779158,  97.08640139,
        93.07867978,  83.52151285, 103.90110378, 117.61984053,
       107.53381388, 107.68861527,  99.80391156, 100.39160201,
        88.65195426, 111.42893776,  85.55328206,  83.04626631,
        82.26715966,  89.66326771,  85.8714874 ,  88.26978023,
       105.68236304, 114.79171349,  77.43313648,  99.94304628,
        97.07798451, 116.14262186, 137.86903256, 114.35699344,
        92.60604197,  83.94896281, 111.0137324 ,  87.62590812,
       111.55367495,  92.35503477, 133.00197892,  85.34359425,
        85.70481931, 101.94709965, 124.83492393, 123.21895673,
       102.72234693,  96.87084862,  94.92684284, 107.67801654,
       109.81173156, 134.35601755, 102.93383997, 118.65838909,
       125.43805289, 103.29368573, 103.2621846 ,  74.62359822,
       105.31378261,  92.94329738,  86.0405116 , 118.69234364,
       119.36910435,  89.0631351 ,  95.57451754, 110.30213476,
       108.33546236,  73.36138304,  98.40379427, 102.80398783,
        85.32191334, 126.18505399,  88.99553299, 115.2297639 ,
       112.57840413, 109.07464608,  96.14160313,  80.01572016,
       108.20720423,  78.82029796,  97.2089587 ,  99.15262824,
        92.31310074,  81.0784312 ,  99.95346125, 101.90803996,
       111.88082861,  97.57604207, 112.09217355,  88.47641096,
        82.36664424, 103.71358892,  77.88857354, 106.72209959,
        87.87248576,  64.86786645, 121.12795978,  80.10531717,
        98.16490962, 103.93532024, 114.92016451,  90.81705928,
       123.23606036,  77.44925075, 104.00748946,  80.26086116,
        79.81278732,  66.42118256, 122.10437901, 107.07810545,
        79.43833864,  93.53107488,  99.75574439,  99.22689502,
        83.98216245,  84.57194422, 100.18641821, 133.27526039,
       117.8492317 , 100.86939905, 115.8900242 , 113.67611348,
       108.31513739, 111.89072258,  94.94591695,  88.05253237,
       102.71108879,  92.19112878, 105.91807271, 121.08747516,
        97.67277207,  82.20663779, 102.60801635, 123.97687758,
       104.05195687,  77.30359233, 101.31959996,  91.06190883,
        82.65059976, 118.68215892,  83.57656841, 109.18834898,
        97.57297108, 103.82109992, 115.27790172, 111.8045904 ,
        75.80761132,  98.43652619, 111.16455713, 103.91881011,
        97.03822667,  92.96651631,  92.96986925,  97.77208341,
        86.80144874,  97.4048784 ,  87.71642884, 118.10318109,
       116.14481302,  90.71504602,  84.52331565, 114.78550217,
       108.41767771,  97.28970046,  91.78443056, 101.71540067,
        88.94862609, 103.31147129, 109.56304087,  92.17480756,
        94.96882762,  94.13193839,  98.47107707,  98.29508848,
       118.42702937,  99.33851047, 101.29220667, 111.59657373,
        80.00852   , 118.17181643, 113.86745047, 107.0246656 ,
       103.5993761 , 129.81627097, 122.91893238,  66.98838382,
        96.9539444 , 107.22904899, 106.05466437, 102.17368785,
       103.22371494, 105.69074878,  84.2496298 ,  82.27567008,
        98.29377551, 115.30989124,  90.49629384,  90.38663843,
       126.10465135, 102.16885662, 103.77724758,  74.8022723 ,
        77.48105965, 100.78528891,  77.98740226, 100.75985359,
       101.31886946,  96.32701271,  90.80556482, 112.14539903,
        88.05593102,  90.67731414,  65.80626153,  98.96555289,
       100.84062737,  69.91189197, 108.55482947,  84.24523475,
        77.82332329, 109.13495294,  85.17641673, 123.62793226,
        88.34803634, 116.25909857, 102.26811762,  93.22359837,
        80.27022068,  86.66735121, 113.36032154,  92.46432583,
       112.40542671, 102.0489156 , 115.45757561, 104.78040525,
        96.88613489, 114.16452467, 105.8006929 , 127.62759541,
       108.01560223,  84.73467091,  88.72802789,  96.1296175 ,
        98.98912293, 104.73687552, 102.59143484,  85.39516678,
       115.13160648,  93.9197394 , 100.76016547,  91.02264969,
        86.10868383, 116.3262245 , 103.34914389,  92.36546652,
        82.94685417,  97.06043587,  87.72825678, 116.49604199,
       110.94981646, 105.21805255,  91.60084936,  83.8917907 ,
        98.43931767, 117.0856152 , 121.94490133,  77.24912024,
       106.98927992,  84.76150705,  96.87738646, 109.88305865,
        85.12455601, 119.34001999, 105.6216817 ,  95.15588267,
       113.61540769, 118.07103159,  79.75283718, 104.54975716,
        92.06854109, 118.06583371,  99.07549278, 104.07597163,
        83.04102202,  83.75026001, 110.20403345,  83.50214223,
       108.04975604,  67.95726221, 104.1708819 ,  81.6955534 ,
       105.34571598,  90.01491128,  73.62186875, 105.78251573,
       106.4492592 , 119.76189729,  98.82596773, 111.52375042,
        89.11692077, 115.92760793,  89.90659449,  73.37012073,
        91.68765945,  91.79137616, 104.07303967, 107.05657129,
        84.96801245,  85.15392449,  87.19105537, 103.60116676,
       103.17093837,  85.32550184,  86.29369315,  98.29537977,
       103.0773975 , 127.03095759, 106.13071364,  95.07203799,
       113.12706902, 151.89516278,  79.66083706,  97.83986374,
       109.29242476,  97.03306641,  99.41895413, 104.54749809,
        99.92434827,  97.26292875, 123.48799627, 133.90751913,
        96.87363801,  90.57634006,  96.51478785,  78.32422749,
       136.45104589,  93.05835509, 106.57042184,  77.82962362,
        81.79652097, 121.84110031,  97.95029068, 106.4959171 ,
        96.02030087, 115.49431859, 106.33068161,  99.43662931,
       105.92304994,  81.03099847, 107.16274369,  81.0793288 ,
       109.34975461, 105.37686934,  90.17927056, 126.33884866,
        86.24238124, 118.66442957, 113.6728024 ,  91.22912182,
       109.70331306, 109.70371853,  97.4082249 ,  94.25206909,
       102.93275025, 104.52961158, 100.21269504, 101.62299953,
       116.48053659, 107.80781936,  85.6568249 , 105.12996957,
       132.76394372, 109.43363832, 107.50256664,  87.09707238,
        96.79859529, 106.42944064, 105.22856722, 115.18339993,
       105.16621321, 112.32222462,  75.03667901, 104.64657582,
        66.67245874,  91.6972949 , 102.89766009,  98.20263462,
       118.18370478,  93.99705503, 120.46616272, 110.39881326,
       103.45681708,  89.92618864,  94.76392945,  95.10444125,
       103.61259329,  98.83546631, 105.37612483, 140.60884157,
       109.0803133 ,  80.19827155,  83.72759136,  81.86316617,
        78.76658617, 104.05298221,  98.15190334,  67.62744032,
        92.94261738,  97.69872199, 115.42875065, 107.03038135])

Compute the **mean**, **median**, and **mode**

In [21]:
mean = np.mean(samples)
median = np.median(samples)
mode = stats.mode(samples)

In [22]:
mean

99.57831247365986

In [23]:
median

99.96446423522144

In [24]:
mode

ModeResult(mode=array([52.2603512]), count=array([1]))

Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [25]:
samples.min()
# np.min(samples)

52.260351200538224

In [26]:
samples.max()
# np.max(samples)

151.89516277605512

In [27]:
np.percentile(samples, 25)

89.76207643014058

In [28]:
np.percentile(samples, 75)

108.72832997333317

In [29]:
np.percentile(samples, [25, 75]) # for both of them at once

array([ 89.76207643, 108.72832997])

In [30]:
iqr = np.percentile(samples, 75)-np.percentile(samples, 25)
iqr

# stats.iqr(samples)

18.966253543192593

Compute the **variance** and **standard deviation**

In [35]:
variance = np.var(samples)  # # "np.var(samples, ddof=1)" for sample
std_dev = np.std(samples)  # "np.std(samples, ddof=1)" for sample

In [36]:
variance

212.49425658205593

In [37]:
std_dev

14.577182738171869

Compute the **skewness** and **kurtosis**

In [42]:
skewness = stats.skew(samples)  # "stats.skew(samples, bias=False)" for sample
kurtosis = stats.kurtosis(samples)  # "stats.kurtosis(samples, bias=False)" for sample

In [43]:
skewness

0.047176924401094764

In [44]:
kurtosis

0.2094385899465192

## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [72]:
x = np.arange(10, 20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [71]:
y = np.array([20, 48, 34, 13, 55, 27, 30, 33, 41, 18])
y

array([20, 48, 34, 13, 55, 27, 30, 33, 41, 18])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [73]:
r = np.corrcoef(x, y)
r

array([[ 1.        , -0.06741507],
       [-0.06741507,  1.        ]])

## Pandas Correlation Calculation

Run the code below

In [74]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [75]:
r = x.corr(y)
r

0.7586402890911867

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [77]:
rho = x.corr(y, method="spearman")
rho

0.9757575757575757

## Seaborn Dataset Tips

Import Seaborn Library

In [78]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [79]:
tips = sns.load_dataset("tips")
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [80]:
tips.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [82]:
tips.corr()

            total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000